
# Configuration file for the alt_names experiment

[files]
data_folder_path="E:\\MDR source data\\Geonames\\data"
log_folder_path="E:\\MDR source data\\Geonames\\logs"
output_folder_path="E:\\MDR source data\\Geonames\\outputs"
src_file_name="alternateNamesV2.txt"


[database]
db_host="localhost"
db_user="postgres"
db_password="WinterIsComing!"
db_port=5433
db_name=""